### ISSUE TITLE
View showing all cases with filtering available

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/311#107]
Designs needed that shows all cases filed. 

Should also incorporate the following:
- Default to most recently submitted cases at top of list.

- Ability to filter by case type.

- Display as: 
On desktop: A map and list side by side (potentially map 2/3 page and list 1/3 page)

On mobile: Just show as list. Depending on design display 20-25 per page with pagination

**Comment by fionawhim** [comment]
Equivalent to this page from https://311.boston.gov/

![screen shot 2017-03-15 at 1 37 49 pm](https://cloud.githubusercontent.com/assets/260837/23962482/a5ccf526-0984-11e7-944c-f1928eb632a6.png)

**Comment by sebastianebarb** [comment]
![311 case look up list](https://cloud.githubusercontent.com/assets/20642299/24121239/fc6c9262-0d8d-11e7-8d88-47849d3a735f.png)

**Comment by reillyzlab** [comment]
Possible iterations discussed on 3/20/17 for more exploratory experience: 

1. Show map in background with list in front. As you scroll through the list the map in the background adjusts to given neighborhood.

2. Ability to meet different user needs of wanting to cases by neighborhood/on map and ability to see by list.

**Comment by sebastianebarb** [comment]
![311 case look up copy 2](https://cloud.githubusercontent.com/assets/20642299/24211489/a4389a34-0f02-11e7-813c-1214bea5f2c7.png)
