### ISSUE TITLE
Record not found on case lookup

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/311#108]
Design needed when no record is found on case lookup.

Include some sort of 'error' message and ability to take next action (either look up again, prompt to call 311, any other ideas based on knowledge of data or other designs)

**Comment by fionawhim** [comment]
Currently what this looks like. :)
![screen shot 2017-03-15 at 1 33 01 pm](https://cloud.githubusercontent.com/assets/260837/23962280/f41b76d6-0983-11e7-9daf-0faef79e8219.png)

**Comment by sebastianebarb** [comment]
![311 look up no result](https://cloud.githubusercontent.com/assets/20642299/24112068/c4954650-0d6e-11e7-9b4e-ffaab958c262.png)
@finneganh Let me know if you have more thoughts
