### ISSUE TITLE
Salesforce Chat

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/311#122]
Need to integrate a chat button into the home page of 311.

Pushing button brings up a pop-up to chat with an agent.

Can also have an "offline" version of the button for when chat agents are unavailable.

<img width="743" alt="screen shot 2017-03-13 at 1 48 35 pm" src="https://cloud.githubusercontent.com/assets/260837/23962008/1eb9faee-0983-11e7-8555-9bffe2dee686.png">

**Comment by reillyzlab** [comment]
Additional thoughts:

- Chat button should disappear if chat is not live
- Chat should appear on all pages if live.

**Comment by fionawhim** [comment]
My understanding is we'll do a right-aligned tab.
