### ISSUE TITLE
311 on the go page

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/311#124]
Need an implementation for 311 on the go. Should it come from CMS or be hard-coded?

<img width="1376" alt="screen shot 2017-03-15 at 1 52 19 pm" src="https://cloud.githubusercontent.com/assets/260837/23963120/ae62c7ea-0986-11e7-909b-969e612bd876.png">

- [x] Yellow grid transaction theme
- [x] Need hover treatment from @sebastianebarb 
- [ ] Actual content

**Comment by fionawhim** [comment]
From Matt: should be in the 311 repo, but potentially easily editable (structured data rather than JSX).

**Comment by reillyzlab** [comment]
@finneganh @sebastianebarb adjust icons to match icon structure of boston.gov?
