### ISSUE TITLE
Image upload

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/311#149]
We want to do image upload from desktop.

**Comment by reillyzlab** [comment]
yes

**Comment by fionawhim** [comment]
Implementation blocked on details about Cloudinary from Incapsulate.

**Comment by sebastianebarb** [comment]
![311 persoanl info copy](https://cloud.githubusercontent.com/assets/20642299/24202498/90b0e372-0ee9-11e7-8ac7-4267d691f822.png)
