### ISSUE TITLE
311 On The Go content

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/311#186]
Right now we have lorem ipsum underneath the 311 transaction grid. https://cob-311.herokuapp.com/onthego
![screen shot 2017-03-30 at 8 56 27 am](https://cloud.githubusercontent.com/assets/260837/24505130/c7c5464e-1526-11e7-9ef6-ecfd0c97bc76.png)

**Comment by reillyzlab** [comment]
@jduffy2001 could you help us draft content for this?

**Comment by fionawhim** [comment]
This is going to be merged with the FAQ page, per recent discussion.

**Comment by reillyzlab** [comment]
Getting updated comps: https://github.com/CityOfBoston/design-team-workflow/issues/297

**Comment by duffy-james** [comment]
@finneganh @reillyzlab Do you still need copy for this?

**Comment by fionawhim** [comment]
I think we'll have to see w/ the new design. If we just want the 4 boxes
and app store buttons on top of the FAQ, then we don't need this graf.
Deferring to Reilly and Sebastian.

**Comment by reillyzlab** [comment]
I'll also defer to @sebastianebarb - but might make sense to see how design ends up before asking you to spending time on it

**Comment by fionawhim** [comment]
Collapsed on the go into FAQ, so we don't need more content.
