### ISSUE TITLE
Image upload design

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/311#190]
Sebastian taking another look at image upload button / drop target design.

**Comment by sebastianebarb** [comment]
https://drive.google.com/open?id=0B0RwQU94BhGeQVRmMnk1eTlhUUE
![upload imige](https://cloud.githubusercontent.com/assets/20642299/24724515/5f795e8e-1a19-11e7-9564-924649fce797.png)

![upload imige interact](https://cloud.githubusercontent.com/assets/20642299/24724517/61c93614-1a19-11e7-8286-31e2d9c3f379.png)

**Comment by fionawhim** [comment]
Still need treatment for the upload button and remove, possibly on top of the image.

**Comment by fionawhim** [comment]
![removephoto](https://cloud.githubusercontent.com/assets/260837/24972842/c35e0b68-1f8a-11e7-8853-9cc815d17696.png)
![photobutton drag](https://cloud.githubusercontent.com/assets/260837/24972843/c360e338-1f8a-11e7-8673-84384cf5a8bc.png)
![photobutton](https://cloud.githubusercontent.com/assets/260837/24972844/c3639268-1f8a-11e7-89f2-c7e7780bdead.png)

**Comment by fionawhim** [comment]
Additionally:
 - Make an "Upload Photo" button that looks like "Remove Photo"
 - Use that area to do the progress bar during upload
