### ISSUE TITLE
Change functionality of translate drop down for 311

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/311#211]
Change functionality of translate drop down for 311 to be different than that of boston.gov.

Ideally, someone would click the word 'translate', select the language that they're hoping for support, and a screen would pop up in that language with instructions on how to contact 311 for help.

@sebastianebarb help with design - https://github.com/CityOfBoston/design-team-workflow/issues/293

**Comment by fionawhim** [comment]
![196c5e50-25c2-11e7-8bab-6c04f54c425c](https://cloud.githubusercontent.com/assets/260837/25756249/1302a00a-3194-11e7-8631-b3b2c68905d3.png)

**Comment by reillyzlab** [comment]
For this, we should remove the 'English' button and rather say 'continue in english'.

We should also add in 'traditional and simplified chinese' as two additional options. Reilly will need to get the verbiage/characters for the chinese translation buttons
