### ISSUE TITLE
Adjust description text on contact form

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/311#223]
We need to update the text in the description of the contact form [see top right below header]:

[Contact Form 311.pdf](https://github.com/CityOfBoston/311/files/910344/Contact.Form.311.pdf)

We need to do a better job explaining why it's important for people to provide us with their contact information. I.e. We need to get back in touch with you to figure out where the needs were located if you submitted a needle removal case. 

But, we also need to emphasize that we don't publicly display contact information. I.e. If I submit something about my neighbor's trash, yard, or car they aren't going to get mad at me for reporting.

**Comment by reillyzlab** [comment]
@jduffy2001 can you help with this

**Comment by fionawhim** [comment]
![screen shot 2017-04-14 at 3 55 11 pm](https://cloud.githubusercontent.com/assets/260837/25054872/8719e34e-212d-11e7-826f-1e27243f7763.png)

**Comment by duffy-james** [comment]
@finneganh @reillyzlab Sorry I didn't comment sooner. Like what you have so far, Fin. There's a small typo, and I'm not sure on whether we should just spell out information. Here's a potential re-write:

"Why are we asking for your contact information? We’ll use it to email you about the status of your report. We may also have to follow up with you.

We won’t make your information public. You can also send a report without giving us your information."

**Comment by reillyzlab** [comment]
Thanks @jduffy2001 - @finneganh can you switch this text out next week?

**Comment by fionawhim** [comment]
<img width="1153" alt="screen shot 2017-05-15 at 11 08 25 am" src="https://cloud.githubusercontent.com/assets/260837/26064417/e3edf652-395e-11e7-930f-7c28a07d5d4e.png">
