### ISSUE TITLE
Icons for common services

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/311#227]
We could have icons for common services that we used instead of the gray 311 icon when there's no image available. We could also use the icon elsewhere in the app. (E.g. the questions page, or on case lookup.)

<img width="883" alt="screen shot 2017-04-10 at 11 47 12 am" src="https://cloud.githubusercontent.com/assets/260837/24870204/90534560-1de3-11e7-985f-52ff8880cf28.png">

At some zoom levels we could put the icons in the waypoint pins as well.

**Comment by reillyzlab** [comment]
Related to: https://waffle.io/CityOfBoston/design-team-workflow/cards/59b80c0348606600774223c9

**Comment by reillyzlab** [comment]
Closing to limit backlog. Will potentially come back to.
