### ISSUE TITLE
Prompt for other cities if not in Boston

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/311#229]
If the user clicks on a location outside of Boston, or if there's some other geolocation indicator earlier in the process, we could point them to 311-equivalent services in neighboring municipalities.

**Comment by reillyzlab** [comment]
Cambridge City Hall: (617) 349-4000
Revere City Hall: (781) 286-8100
Lynn City Hall: (781) 598-4000
Quincy City Hall: (617) 376-1000
Chelsea City Hall: (617) 466-4000
Brookline City Hall:  (617) 730-2000
Dedham City Hall: (781) 751-9100
Winthrop City Hall: (617) 846-1852 
Lowell City Hall: (978) 970-4000
Lawrence City Hall: (978) 620-3000
Worcester City Hall: (508) 929-1300
Springfield City Hall: (413) 736-3111
Somerville City Hall: (617) 666-3311 [their 311 service]
Milton Town Hall: 617-898-4800

sent 311 follow up question on other agencies, such as MBTA, Massport, state

**Comment by fionawhim** [comment]
Gonna wait for parks thing to sort out before going deeper on "outside of Boston" code.

**Comment by fionawhim** [comment]
Fixed in #823
