### ISSUE TITLE
Update search messaging

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/311#265]
Search on the home page should take case numbers as well as addresses. If an address matches, should focus on that area.

**Comment by reillyzlab** [comment]
On 'search cases', we should adjust search to accommodate:
- When a user searches a keyword that does not have any corresponding results: A 'no results' message should appear where search results would have appeared.
- When a user searches with what appears to be a case number, but there are no corresponding results a user should be prompted with a message to call 311 for more help. 
- When a user searches what appears to be a location, the map should focus on the area (like is stated above)

@jduffy2001 can you help @finneganh with wording for these messages?

**Comment by duffy-james** [comment]
**Keyword no results:**

"Your search didn't return any results. Please first make sure you spelled everything correctly. You can also use different words, more general words, or fewer words.

If you still can't find what you're looking for, try clicking on the map. You'll see cases reported in the area where you click."

**No case number result**

"Your case number search didn't return any results. Please contact BOS:311 at 3-1-1 or 617-635-4000 for help."
