### ISSUE TITLE
Design for expanded all services category

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/311#275]
Need to see what the list of services looks like when a category is expanded.

![all service requests](https://cloud.githubusercontent.com/assets/260837/25133745/98fa62aa-241b-11e7-82b6-b1f33557f9c6.png)

**Comment by fionawhim** [comment]
![expanded](https://cloud.githubusercontent.com/assets/20642299/25200680/38fdd80c-251d-11e7-9a88-7d09d4c1948d.png)

**Comment by sebastianebarb** [comment]
![311 page all services](https://cloud.githubusercontent.com/assets/20642299/26417431/318b7a4a-4087-11e7-8f9e-9e3dcab50f07.png)
@finneganh would love thoughts

**Comment by fionawhim** [comment]
I think "frequently used" is out-of-scope right now. We also don't have a secondary category like "Trash".

**Comment by sebastianebarb** [comment]
@finneganh 
roger, let's call "frequently used" future state and remove secondary category till we need it (if at all)
