### ISSUE TITLE
Automatic list of top requests

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/311#303]
The most popular requests list on the homepage should be automatically populated based on actual top requests.

**Comment by fionawhim** [comment]
Emailed Luis on 4/24

**Comment by fionawhim** [comment]
Blocked on API from data team.

**Comment by fionawhim** [comment]
Removing milestone and requirement. Per discussion with @reillyzlab we're going to start with a static list of top requests and consider this a post-launch improvement if it's necessary.

**Comment by reillyzlab** [comment]
Closing to limit backlog. Will potentially come back to.
