### ISSUE TITLE
Designs for All Data types

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/311#35]
- [x] Get list of all data types
- [x] Send it to Sebastian
- [x] Waiting on more designs

### Data Types
 - [x] Single Value List (select dropdown)
 - [x] Multi Value List (checkboxes)
 - [x] String (single line)
 - [ ] Datetime
 - [ ] Text (text area)
 - [ ] Informational (help text)

**Comment by fionawhim** [comment]
![group 2](https://cloud.githubusercontent.com/assets/260837/23307258/e0d50df8-fa74-11e6-8629-3a34b330bbf5.png)

**Comment by sebastianebarb** [comment]
@finneganh this should give you info text, date time selector, and text area. I can provide more detail if needed.

![screenshot 2017-02-28 10 46 40](https://cloud.githubusercontent.com/assets/20642299/23412588/f418c6fc-fda3-11e6-81d5-86f93431c5d2.png)
![screenshot 2017-02-28 10 47 55](https://cloud.githubusercontent.com/assets/20642299/23412589/f4418dc6-fda3-11e6-9f7c-fbce0249c91c.png)
