### ISSUE TITLE
Favicon and home screen icon

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/311#357]
The web portal will need a favicon and should also have a nice home screen icon if you add it to your iOS home screen.

**Comment by sebastianebarb** [comment]
![311 page all services](https://cloud.githubusercontent.com/assets/20642299/26417431/318b7a4a-4087-11e7-8f9e-9e3dcab50f07.png)
@finneganh would love thoughts

**Comment by sebastianebarb** [comment]
[3dc14564e61481beeed2470451beaa74.ico.zip](https://github.com/CityOfBoston/311/files/1026690/3dc14564e61481beeed2470451beaa74.ico.zip)
