### ISSUE TITLE
Finalize sample descriptions

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/311#369]
The sample descriptions that cycle through the text box on the home page need to be vetted and finalized.

**Comment by reillyzlab** [comment]
@finneganh I'll get folks in 311 and CRM to look through them but my feedback would be take out the snow plowing one except during the winter

**Comment by reillyzlab** [comment]
From 311 supervisors: We think these are great! One suggestion is that 'Needles in the Park!!!' be changed to 'Needles near the litter basket in the park', as one thing we are always trying to stress to constituents is that we need as specific a location as possible, especially in regard to needles. 

Think this makes sense but please use the following wording:
Needles in the park near the trash can
