### ISSUE TITLE
All Service Requests UI

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/311#45]
![screen shot 2017-03-27 at 3 26 46 pm](https://cloud.githubusercontent.com/assets/260837/24374152/c9520e2e-1301-11e7-99d5-08e79800f7f3.png)

**Comment by fionawhim** [comment]
We don't have the data for this.

**Comment by fionawhim** [comment]
This is what it looks like on the old site.

![screen shot 2017-03-15 at 1 35 02 pm](https://cloud.githubusercontent.com/assets/260837/23962393/5e051782-0984-11e7-89b0-64686f6462d4.png)

**Comment by sebastianebarb** [comment]
![311 page all services](https://cloud.githubusercontent.com/assets/20642299/25200680/38fdd80c-251d-11e7-9a88-7d09d4c1948d.png)

**Comment by fionawhim** [comment]
We need to get a sense of how many SRs per category, so we know whether to do something like the above or carve out space for descriptions for each.

**Comment by fionawhim** [comment]
Blocked on getting Vanessa to load in the data.
