### ISSUE TITLE
Support legacy SR URLs

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/311#583]
If someone follows an old link to a case type we should be able to take them to the new URL.

- [x] Update 311 webapp to translate old service_ids
- [x] Update 311 webapp to handle list_services URL
- [x] Make mayors24 redirector that redirects to 311.boston.gov and also translates Lagan IDs

**Comment by fionawhim** [comment]
Static 311 page: http://www.cityofboston.gov/311/ -> HTTP redirect over to 311.boston.gov

Mayor/24 "topic" redirects: http://www.cityofboston.gov/mayor/24?topic=streetlight -> leave as-is, but deprecate and replace www.boston.gov links to it.

SpotReporter links:
 - https://311.boston.gov/reports/new?service_id=4f389210e75084437f0001d8 -> support static map of service_ids to new case types, redirect within 311 app
 - https://311.boston.gov/reports/list_services

Mayor's 24 site:
 - Redirect SpotReporter links as-is to 311.boston.gov and let 311 webapp handle decoding them
 - Ef3 links:
   - http://mayors24.boston.gov/Ef3/SSP_PWDx02_MissedTrashRecyclingYardWasteBulkItem.xml -> redirect to General.jsp page
   - http://mayors24.boston.gov/Ef3/General.jsp?form=SSP_PWDx02_MissedTrashRecyclingYardWasteBulkItem&page=SSP_Page_EmailEnterNoAnon -> have mapping from "form" IDs to SR types, redirect to 311.boston.gov

**Comment by finneganh** [comment]
- [ ] Update 311 webapp to translate old service_ids
- [ ] Update 311 webapp to handle list_services URL
- [ ] Make mayors24 redirector that redirects to 311.boston.gov and also translates Lagan IDs

**Comment by fionawhim** [comment]
Waiting to hear back from CRM team about mayors24.cityofboston.gov

**Comment by fionawhim** [comment]
Checked in, still needs productionization.
