### ISSUE TITLE
Finalize popular service list

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/311#612]
In lieu of having it auto-populated, we need a curated list of 5 service types we'd like to highlight on the home page.

**Comment by fionawhim** [comment]
Don't forget we also need a strategy to bust the cache of top services.

**Comment by reillyzlab** [comment]
To add:

Top 10 (based on 311 analytics):

1. Parking on Front/Back Yards (Illegal Parking)
Linked to: https://311.digital-staging.boston.gov/request/PRKGENFORC

2. Litter on Street/Sidewalk
Link to: Not on site yet 

3. Schedule a Bulk Item Pickup
Linked to: https://311.digital-staging.boston.gov/request/SCHDBLKITM

4. Request for Pothole Repair
Linked to: https://311.digital-staging.boston.gov/request/REQPOTHL

5. MISSED TRASH, RECYCLING, YARD WASTE, BULK ITEM
Pick up missed trash, recycling, yard waste, or bulk item that was put out before 7am the morning of collection.
Linked to: https://311.digital-staging.boston.gov/request/MTRECYDBI

In case you need more:

6. Improper Storage of Trash (Barrels)
Linked to: https://311.digital-staging.boston.gov/request/IMPSTRTRSH

7. Street Lights Outages
Linked to: https://311.digital-staging.boston.gov/request/STRLGTOUT

8. Missing/Damaged Sign Repair
Linked to: https://311.digital-staging.boston.gov/request/MISDMGSGN

9. Traffic Signal Repair
Linked to: https://311.digital-staging.boston.gov/request/TFCSGNINSP

10. Sidewalk Repair
Linked to: https://311.digital-staging.boston.gov/request/SDWRPR

_Note: We will need to add in seasonal requests manually. Examples: Snow and student move in._
