### ISSUE TITLE
Landing page after submission

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/311#67]
Need a design for the page you land on after submitting a request.

**Comment by sebastianebarb** [comment]
![311 thank you](https://cloud.githubusercontent.com/assets/20642299/24113336/dbe22a04-0d72-11e7-9bdf-f02c676fdedd.png)
@finneganh happy to make changes

**Comment by fionawhim** [comment]
Sebastian is working on a version w/o an image

**Comment by sebastianebarb** [comment]
![311 thank you no photos](https://cloud.githubusercontent.com/assets/20642299/24121268/0e365dde-0d8e-11e7-8875-77d1f71717eb.png)

**Comment by reillyzlab** [comment]
Via Slack:

Fin: Also, for that page, what should be done when no location or description? Leave the row blank, don’t show the row, or add some sort of “none” text?

Sebastian Ebarb [1:42 PM] 
Leave the row blank, keep the title
