### ISSUE TITLE
Better no-question experience

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/311#757]
Service types with no questions look awkward and don't seem to have any instructions.

We should make it clearer what you need to do, perhaps by adding instructions or changing the label on the "Description" box.

![311 digital-staging boston gov-request-prkgenforc](https://user-images.githubusercontent.com/260837/31836507-8bf0b482-b5a3-11e7-863d-c28f49548839.png)

**Comment by reillyzlab** [comment]
@sebastianebarb can you put together comp.?

**Comment by reillyzlab** [comment]
@jduffy2001 we're not going to redo design, but can you help think through better language for header that currently reads 'description' and text in the text area box.

Few examples:

- https://311.digital-staging.boston.gov/request/PRKGENFORC

- https://311.digital-staging.boston.gov/request/RATBITE
