### ISSUE TITLE
Fix styling of live chat 

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/311#770]
Fix styling of live chat so that it doesn't show right next to 'start a request' like this:

![screen shot 2017-10-25 at 12 22 10 pm](https://user-images.githubusercontent.com/20731897/32010242-41672fa6-b97f-11e7-8b48-c75c3714f693.png)

**Comment by fionawhim** [comment]
![localhost-3000- 2](https://user-images.githubusercontent.com/260837/32118133-a0aaea7a-bb1e-11e7-9b15-3944d34bbd4f.png)
