### ISSUE TITLE
Map display: Fix color display of Long and Thompson Islands

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/311#771]
On map, Long Island on the map is listed in black - all other cities are gray. This should be changed so that Long and Thompson Islands words match the other colors and become gray.

![screen shot 2017-10-25 at 2 52 17 pm](https://user-images.githubusercontent.com/20731897/32017252-20cd6412-b994-11e7-9990-714cb5535c53.png)

**Comment by carolinestj** [comment]
Should be fixed on my end now, don't know how long it takes for it to update

**Comment by fionawhim** [comment]
I was able to verify the fix on the staging environment.

<img width="700" alt="screen shot 2017-10-27 at 11 10 29 am" src="https://user-images.githubusercontent.com/260837/32111097-833610b2-bb07-11e7-8219-a1faf753cfa3.png">
