### ISSUE TITLE
Adjust photos API

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/311#871]
Adjust photos API to consume 'all photos' in system (i.e. all case level and activity level photos).

See Chris H. for more details. 

Not urgent -- 'before go live', but affects change in case emails, so sooner than later ideal.

- May need to adjust multi-photo display when do this

**Comment by fionawhim** [comment]
Ping out to Chris/Vanessa to get a case to test this with.

**Comment by fionawhim** [comment]
Case #: 18-00012429
