### ISSUE TITLE
Adjustments to phone number on contact page

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/311#873]
Problem: There are different phone number formats coming in and being processed from different platforms. This is causing errors in Salesforce.

Overall resolution: All platforms are going to have a +1 added in front of all phone numbers.

For website: 
The contact form should be adjusted so that +1 is automatically built into the contact form.
Example of page this affects: https://311.digital-staging.boston.gov/request/MISDMGSGN/contact

We need to ensure that this works:
- [x] By showing up visually on the site
- [x] That the +1 is being sent to Salesforce

**Comment by fionawhim** [comment]
Blocked on Salesforce supporting when we send "+1 (xxx) xxx-xxxx"

<img width="856" alt="screen shot 2018-03-22 at 10 46 50 am" src="https://user-images.githubusercontent.com/260837/37777865-f1507e3c-2dbe-11e8-8ebe-fd587bf56725.png">

**Comment by limadog2003** [comment]
We just implemented a new Trigger that should reformat any valid phone number submitted into a "+1" format, whether the number has no +1, just a 1, or has a +1.  Try retesting now and let me know if you have any problems.
