### ISSUE TITLE
Create fall back page/message if the site goes down

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/311#929]
If site goes down, mimic the content on the 'translate' portion of the site as a fall back option.

![screen shot 2018-11-06 at 10 36 33 am](https://user-images.githubusercontent.com/20731897/48074912-f7ef9480-e1af-11e8-9985-576ac5bdfcd4.png)

**Comment by fionawhim** [comment]
<img width="1426" alt="screen shot 2018-12-05 at 1 55 18 pm" src="https://user-images.githubusercontent.com/260837/49536976-c8f33e00-f895-11e8-8a8d-8c06a0d8b58c.png">

**Comment by fionawhim** [comment]
I've set it up as a sorry page we can toggle on via .env and restarting the servers.
