### ISSUE TITLE
Language on photo on case details page

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/311#931]
On all photos on the 'case details' page,

When someone uploads a photo it's added/stored but right now there is an 'open' label hovering on the bottom

And, when a worker adds a photo it's added/stored but right now there is an 'updated' label hovering on the bottom

Example: 
https://311-uat.digital-staging.boston.gov/reports/200983595

![screen shot 2018-11-06 at 11 03 34 am](https://user-images.githubusercontent.com/20731897/48076650-a0ebbe80-e1b3-11e8-9b8f-11235d962d5f.png)

This should be adjusted so that the 'open' language says 'your photo' and the 'updated' languages says 'our photo'.

If possible, these labels should become plural if there is more than one photo.

**Comment by fionawhim** [comment]
Kicking this back to @reillyzlab because "Your photo" seems a bit off when looking at someone else’s case.

**Comment by fionawhim** [comment]
"Original Submission" and "Resolution"
