### ISSUE TITLE
Potential issue when selecting a park with cursor

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/311#936]
When a user is in the map view and clicks on Boston Common (a park) with a cursor the results should say "Boston Common". Instead, the results turn back '139 tremont st'

Unsure whether this is a site issue or GIS Issue. Will need dev. to dive in to research a little more.

![screen shot 2018-11-07 at 4 34 08 pm](https://user-images.githubusercontent.com/20731897/48162698-c65bf380-e2ab-11e8-88df-b1f64cd23c3c.png)

https://311-uat.digital-staging.boston.gov/reports/200983652

If a user searches for 'Boston Common' in the search field 'Boston Common' will be returned as the location.

**Comment by fionawhim** [comment]
I think the layer number for Open Spaces has changed again. The current code uses "31" but that’s returning 400 responses.

Email out to geo team to find out what the latest is. Blocked on their response.
