### ISSUE TITLE
Location: Issue when submitting as park and it coming up as alternate address

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/311#937]
When a user can select a park as the park name (Boston Common) and submits a case with that park the case submission is processed, but on the 'case details' page the park name disappears and an alternative address appears.

The park name should remain on the case details page and not be replaced by an alternative address.

Example: https://311-uat.digital-staging.boston.gov/reports/200983656

**Comment by fionawhim** [comment]
This _may_ be "working as intended."

In park cases, we’re sending lat/lng when creating the case. It’s up to the Salesforce side to interpret that how it will.

**Comment by reillyzlab** [comment]
The case details should be displaying the park name. CRM/GIS folks are looking into the cause/resolution.

**Comment by fionawhim** [comment]
OK. For these cases we're just sending lat/lng for creation.

LMK if they say it would be better for us to send the name of the park instead (though that would then lose the lat/lng within the park, e.g. if the person clicked near the frog pond specifically).

**Comment by fionawhim** [comment]
Blocked on CRM / GIS looking into it.
